
all:
	 g++ -I ./../Sockets/ -std=c++11 -pthread -c receiveFromClient.cpp -o receiveFromClient.o
	 # g++ -I ./../Sockets/ receiveFromClient.o ./../Sockets/tcp_socket.o 
	#g++ load_distributer.cpp -o load_distributer.o

clean:
	rm *.o